name: Python code quality check

on:
  push:
    branches: [main, "*dev"]
  pull_request:
    branches: [main, "*dev"]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff ./python"
          version: "latest"
